blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
blogger_blog_about:
    path:     /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
blogger_blog_contact:
    path:     /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
      _method: GET|POST
blogger_blog_show:
    path:     /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    methods: GET
    requirements:
      id: \d+
blogger_comment_create:
    path:     /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    methods: POST
    requirements:
      blog_id: \d+
blogger_blog_faq:
    path:     /faq
    defaults: { _controller: BloggerBlogBundle:Page:faq }
blogger_blog_newBlog:
    path:     /newBlog
    defaults: { _controller: BloggerBlogBundle:Blog:newBlog }
    requirements:
      _method: GET|POST